version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ss_auth
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  business:
    build:
      context: ./business
      dockerfile: Dockerfile
    image: springsecurity/business:1.0
    container_name: business
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      AUTHENTICATE_SERVER_BASE_URL: http://auth:8080
    networks:
      - backend

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: springsecurity/auth:1.0
    container_name: auth
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ss_auth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: backend
    driver: bridge