apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql...; sleep 2; done']
      containers:
        - name: auth
          image: ghcr.io/grapeppodo/auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SPRING_PROFILES_ACTIVE
            - name: AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: AUTH_SERVER_URL
            - name: JWT_SIGNING_KEY
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: JWT_SIGNING_KEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/ss_auth
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: SPRING_DATASOURCE_PASSWORD
