apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  type: NodePort
  selector:
    app: business
  ports:
    - port: 9090 # 클러스터 내 서비스 포트
      targetPort: 9090 # 실제 앱 포트 (컨테이너 내부)
      nodePort: 30002
